### ISSUE TITLE
Error on Setup Docker

### ISSUE THREAD

**Issue by mohamed-abdul-fattah** [mohamed-abdul-fattah/jira-logger#32]
On fresh docker install, this error appears on running
```
> docker logs jiralogger-cli
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. It is recommended that you run `composer update` or `composer update <package name>`.
Nothing to install or update
Generating autoload files
Traceback (most recent call last):
	5: from /usr/local/bin/overcommit:23:in `<main>'
	4: from /usr/local/bin/overcommit:23:in `load'
	3: from /var/lib/gems/2.5.0/gems/overcommit-0.52.1/bin/overcommit:50:in `<top (required)>'
	2: from /var/lib/gems/2.5.0/gems/overcommit-0.52.1/lib/overcommit/cli.rb:24:in `run'
	1: from /var/lib/gems/2.5.0/gems/overcommit-0.52.1/lib/overcommit/cli.rb:115:in `install_or_uninstall'
/var/lib/gems/2.5.0/gems/overcommit-0.52.1/lib/overcommit/utils.rb:50:in `repo_root': Unable to determine location of GIT_DIR. Not a recognizable Git repository! (Overcommit::Exceptions::InvalidGitRepo)
```

**Comment by mohamed-abdul-fattah** [comment]
As per [Overcommit exceptions documentation](https://www.rubydoc.info/github/brigade/overcommit/Overcommit/Exceptions/InvalidGitRepo), this error is raised because of the project directory is not a git repo.
